<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="s" uri="/struts-tags"%>
<div>
	<s:i18n name="translate/hibernate/hibernate-release-4_3_6_Final/c22">
		<div>
			<h1 id="c22"><s:text name="title22" /></h1>
		</div>
		<div>
			<h2 id="c22-1"><s:text name="title22-1" /></h2>
			<p><s:text name="p22-1-1" /></p>
			<p><s:text name="p22-1-2" /></p>
			<p><s:text name="p22-1-3" /></p>
			<p><s:text name="p22-1-4" /></p>
		</div>
		<div>
			<h3 id="c22-1-1"><s:text name="title22-1-1" /></h3>
			<p><s:text name="p22-1-1-1" /></p>
		</div>
		<div>
			<h3 id="c22-1-2"><s:text name="title22-1-2" /></h3>
			<p><s:text name="p22-1-2-1" /></p>
			<p><s:text name="p22-1-2-2" /></p>
			<p><s:text name="p22-1-2-3" /></p>
			<ul>
				<li><s:text name="li22-1-2-1-1" /></li>
				<li><s:text name="li22-1-2-1-2" /></li>
				<li><s:text name="li22-1-2-1-3" /></li>
				<li><s:text name="li22-1-2-1-4" /></li>
			</ul>
			<div class="alert alert-info" role="alert">
			    <h5 class="lead"><span class="glyphicon glyphicon-info-sign"></span> <s:text name="note" /></h5>
			    <p><s:text name="nc22-1-2-1" /></p>
			    <pre xmlns="" class="XML">
<!-- XML : generated by JHighlight v1.0 (http://jhighlight.dev.java.net) -->
<span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">persistence</span><span class="xml_plain">&nbsp;...</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">persistence-unit</span><span class="xml_plain">&nbsp;...</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;...</span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">properties</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">property</span><span class="xml_plain">&nbsp;</span><span class="xml_attribute_name">name</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"javax.persistence.validation.mode"</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_attribute_name">value</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"callback,&nbsp;ddl"</span><span class="xml_tag_symbols">/&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">properties</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">persistence-unit</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">persistence</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
</pre>
				<p><s:text name="nc22-1-2-2" /></p>
			</div>
			<p><s:text name="p22-1-2-4" /></p>
			<ul>
				<li><s:text name="li22-1-2-2-1" /></li>
				<li><s:text name="li22-1-2-2-2" /></li>
				<li><s:text name="li22-1-2-2-3" /></li>
				<li><s:text name="li22-1-2-2-4" /></li>
			</ul>
			<p><s:text name="p22-1-2-5" /></p>
			<div class="example"><a id="d5e9907"></a><a id="d5e9956"><p class="title"><strong>Example&nbsp;22.1.&nbsp;Using custom groups for validation</strong></p><div class="example-contents">
        

        <pre xmlns="" xmlns:d="http://docbook.org/ns/docbook" xmlns:rf="java:org.jboss.highlight.XhtmlRendererFactory" class="XML">
<!-- XML : generated by JHighlight v1.0 (http://jhighlight.dev.java.net) -->
<span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">persistence</span><span class="xml_plain">&nbsp;...</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">persistence-unit</span><span class="xml_plain">&nbsp;...</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;...</span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">properties</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">property</span><span class="xml_plain">&nbsp;</span><span class="xml_attribute_name">name</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"javax.persistence.validation.group.pre-update"</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_attribute_name">value</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"javax.validation.group.Default,&nbsp;com.acme.group.Strict"</span><span class="xml_tag_symbols">/&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">property</span><span class="xml_plain">&nbsp;</span><span class="xml_attribute_name">name</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"javax.persistence.validation.group.pre-remove"</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_attribute_name">value</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"com.acme.group.OnDelete"</span><span class="xml_tag_symbols">/&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;</span><span class="xml_tag_name">property</span><span class="xml_plain">&nbsp;</span><span class="xml_attribute_name">name</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"org.hibernate.validator.group.ddl"</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_attribute_name">value</span><span class="xml_tag_symbols">=</span><span class="xml_attribute_value">"com.acme.group.DDL"</span><span class="xml_tag_symbols">/&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">properties</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_plain">&nbsp;&nbsp;</span><span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">persistence-unit</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
<span class="xml_tag_symbols">&lt;/</span><span class="xml_tag_name">persistence</span><span class="xml_tag_symbols">&gt;</span><span class="xml_plain"></span><br>
</pre>
      </div></a></div>
			<div class="alert alert-info" role="alert">
			    <h5 class="lead"><span class="glyphicon glyphicon-info-sign"></span> <s:text name="note" /></h5>
			    <p><s:text name="nc22-1-2-3" /></p>
			</div>
		</div>
		<div>
			<h3 id="c22-1-3"><s:text name="title22-1-3" /></h3>
			<p><s:text name="p22-1-3-1" /></p>
			<p><s:text name="p22-1-3-2" /></p>
			<p><s:text name="p22-1-3-3" /></p>
		</div>
		<div>
			<h3 id="c22-1-4"><s:text name="title22-1-4" /></h3>
			<p><s:text name="p22-1-4-1" /></p>
			<ul>
				<li><s:text name="li22-1-4-1-1" /></li>
				<li><s:text name="li22-1-4-1-2" /></li>
				<li><s:text name="li22-1-4-1-3" /></li>
				<li><s:text name="li22-1-4-1-4" /></li>
			</ul>
			<p><s:text name="p22-1-4-2" /></p>
			<p><s:text name="p22-1-4-3" /></p>
		</div>
		<div>
			<h2 id="c22-2"><s:text name="title22-2" /></h2>
		</div>
		<div>
			<h3 id="c22-2-1"><s:text name="title22-2-1" /></h3>
			<p><s:text name="p22-2-1-1" /></p>
		</div>
		<div>
			<h3 id="c22-2-2"><s:text name="title22-2-2" /></h3>
			<p><s:text name="p22-2-2-1" /></p>
			<p><s:text name="p22-2-2-2" /></p>
		</div>
	</s:i18n>
</div>